---
apiVersion: v1
kind: Namespace
metadata:
  name: manawa-gke
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: google-sync
  name: google-sync
  namespace: manawa-gke
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: google-sync
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: google-sync
    spec:
      containers:
        - image: google/cloud-sdk
          command: ["/bin/sh", "-c"]
          args:
            [
              "curl -o /usr/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x /usr/bin/kubectl;while true;do curl https://gist.githubusercontent.com/xavierbaude/9b47fc80a1ce2309fc3be319e761a068/raw/0ba3ea794bf91b12f5df2a7f2d2a05237f94ea98/secretgitops.sh -o /entrypoint.sh ; chmod +x /entrypoint.sh; /entrypoint.sh;done",
            ]
          imagePullPolicy: IfNotPresent
          name: google-sync
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-sync
  name: vault-sync
  namespace: manawa-gke
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vault-sync
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault-sync
    spec:
      containers:
        - image: bitnami/kubectl
          args:
            - create
            - secret
            - generic
            - clouddns-dns01-solver-svc-acct
            - --from-file=monsecret=/var/run/vault
            - -n
            - traefik-public
          imagePullPolicy: IfNotPresent
          name: kubectl
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: vault-secrets
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: jfrog-registry
      initContainers:
        - args:
            - -kubeAuthRole
            # name of the "Module name" in Vault Editor (see step 2)
            - manawa-gke
            - -secrets
            # full path of secret you want to access with secret/data/* prefix
            - secret/data/cluster-xavier#key
            - -out
            # the path where secrets are stored
            - /var/run/vault
            - -url
            - https://vault.factory.adeo.cloud
            - -kubeAuthPath
            # the auth name (check step 1)
            - manawa-sbx-sp-dtep-xavier
            - -namespace
            # The Vault namespace
            - adeo/manawa-gke
          image: adeo-docker-public.jfrog.io/dockerfiles-collection/kube-vault-client:latest
          imagePullPolicy: Always
          name: vault-authenticator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: vault-secrets
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: vault-secrets
