---
apiVersion: v1
kind: Namespace
metadata:
  name: manawa-gke
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: google-sync
  name: google-sync
  namespace: manawa-gke
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: google-sync
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: google-sync
    spec:
      containers:
        - image: bitnami/kubectl
          args:
            - create
            - secret
            - generic
            - clouddns-dns01-solver-svc-acct-google
            - --from-file=monsecret=/var/run/vault
            - -n
            - traefik-public
          imagePullPolicy: IfNotPresent
          name: kubectl
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: vault-secrets
      dnsPolicy: ClusterFirst
      initContainers:
        - image: google/cloud-sdk
          args:
            - secrets
            - versions
            - access
            - version-id
            - --secret="secret-id"
            - >
            - /var/run/vault
          imagePullPolicy: IfNotPresent
          name: gcloud
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: vault-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: vault-secrets
