apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-admin
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services", "serviceaccounts","configmaps","secrets","persistentvolumeclaims","replicasets","horizontalpodautoscalers","cronjobs","jobs","poddisruptionbudgets","rolebindings"]
  verbs: ["create","get", "list", "watch","patch","update","delete","deletecollection"]